databases:
  - name: mydb
    plan: free
    databaseName: mydb
    user: mumm

services:
  - type: web
    plan: free
    name: TDM-Photography
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn photo_site.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
