# Generated by Django 5.0.6 on 2024-05-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/album_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WelcomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to TDM Photography', max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='media/welcome/')),
                ('background_image_2', models.ImageField(blank=True, null=True, upload_to='media/welcome/')),
                ('background_image_3', models.ImageField(blank=True, null=True, upload_to='media/welcome/')),
                ('background_image_4', models.ImageField(blank=True, null=True, upload_to='media/welcome/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='media/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_album_photos', to='gallery.album')),
                ('albums', models.ManyToManyField(related_name='album_photos', to='gallery.album')),
                ('tags', models.ManyToManyField(blank=True, to='gallery.tag')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
