# Generated by Django 5.0.6 on 2024-06-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_name_photo_url_sharedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.DeleteModel(
            name='SharedLink',
        ),
    ]
