# Generated by Django 5.0.6 on 2025-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_folder_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/folder_covers/'),
        ),
    ]
