# Generated by Django 5.0.6 on 2024-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_album_options_album_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepagesettings',
            name='background_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='welcome_backgrounds/'),
        ),
        migrations.AddField(
            model_name='welcomepagesettings',
            name='background_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='welcome_backgrounds/'),
        ),
    ]
