# Generated by Django 5.0.6 on 2024-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_welcomepagesettings_background_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepagesettings',
            name='background_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='welcome_backgrounds/'),
        ),
    ]
