# Generated by Django 5.0.6 on 2024-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_welcomepagesettings_background_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/album_covers/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome_backgrounds/'),
        ),
    ]
