# Generated by Django 5.0.6 on 2024-05-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_album_cover_image_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepagesettings',
            name='title',
            field=models.CharField(default='Welcome to TDM Photography', max_length=100),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome/'),
        ),
        migrations.AlterField(
            model_name='welcomepagesettings',
            name='background_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/welcome/'),
        ),
    ]
